# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 码农修行手册
subtitle: Python与量子计算之路上的心得与实践
description: moye12325的个人技术博客，专注于Python、全栈开发实战经验、编程技巧分享与深入的技术解析。
keywords: Python, 全栈开发, 编程学习, 技术分享, moye12325
author: moye12325
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://moye12325.github.io
root: /
permalink: posts/:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: false

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# SEO
feed:
  type: atom
  path: atom.xml
  limit: 20

sitemap:
  path: sitemap.xml
  rel: true
  tags: true
  categories: true

# Extensions
theme: redefine

# Theme configuration overrides
theme_config:
  info:
    title: 码农修行手册
    subtitle: Python与量子计算之路上的心得与实践
    author: moye12325
    url: https://moye12325.github.io
  global:
    open_graph:
      enable: true
      image: /images/redefine-og.webp
      description: moye12325的个人技术博客，专注于Python、全栈开发实战经验、编程技巧分享与深入的技术解析。

# Deployment
deploy:
  type: git
  repo: git@github.com:moye12325/moye12325.github.io.git
  branch: gh-pages
